
server:
  port: 8988

spring:
  application:
    name: server-mybatis



#datasource config
jdbc:
  driverClassName: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@10.73.18.177:1521:jxxyw01
  username: jxzmccos
  password: soccmzxj_2010

#mybatis config
mybatis:
  typeAliasesPackage: com.example.servermybatis.entity
  mapperLocations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8888/eureka/
  instance:
      prefer-ip-address: true  # 使用ip地址注册到eureka server
      instance-id: ${spring.cloud.client.ipAddress}:${server.port} # 在eureka server中看到的status显示为具体的ip地址和port



