package com.example.server.entity;

import java.util.Date;

public class WgArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.AREA_ID
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.AREA_NAME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.AREA_LEVEL
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private String areaLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.AREA_TYPE
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private String areaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.AREA_PID
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private String areaPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.CREATE_TIME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.CREATOR
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.AREA_CODE
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.MAP_LEVEL
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private String mapLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.AREA_INFO
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private String areaInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.WG_PID
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private String wgPid;
    
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.LEFTTOPX
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private Double lefttopx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.LEFTTOPY
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private Double lefttopy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.RIGHTBOTTOMX
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private Double rightbottomx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.RIGHTBOTTOMY
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private Double rightbottomy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.PROC_TIME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private Date procTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##JXYD_ZHWG.WG_AREA.AREA_LOCATION
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    private String areaLocation;
    
    private String teleNum;
    private String roleId;
    
    private String userCode;
    private String kpiType ;
    private String kpiValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_ID
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.AREA_ID
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_ID
     *
     * @param areaId the value for C##JXYD_ZHWG.WG_AREA.AREA_ID
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_NAME
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.AREA_NAME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_NAME
     *
     * @param areaName the value for C##JXYD_ZHWG.WG_AREA.AREA_NAME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_LEVEL
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.AREA_LEVEL
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public String getAreaLevel() {
        return areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_LEVEL
     *
     * @param areaLevel the value for C##JXYD_ZHWG.WG_AREA.AREA_LEVEL
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setAreaLevel(String areaLevel) {
        this.areaLevel = areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_TYPE
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.AREA_TYPE
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_TYPE
     *
     * @param areaType the value for C##JXYD_ZHWG.WG_AREA.AREA_TYPE
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setAreaType(String areaType) {
        this.areaType = areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_PID
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.AREA_PID
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public String getAreaPid() {
        return areaPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_PID
     *
     * @param areaPid the value for C##JXYD_ZHWG.WG_AREA.AREA_PID
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setAreaPid(String areaPid) {
        this.areaPid = areaPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.CREATE_TIME
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.CREATE_TIME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.CREATE_TIME
     *
     * @param createTime the value for C##JXYD_ZHWG.WG_AREA.CREATE_TIME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.CREATOR
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.CREATOR
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.CREATOR
     *
     * @param creator the value for C##JXYD_ZHWG.WG_AREA.CREATOR
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_CODE
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.AREA_CODE
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_CODE
     *
     * @param areaCode the value for C##JXYD_ZHWG.WG_AREA.AREA_CODE
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.LAST_UPDATE_TIME
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for C##JXYD_ZHWG.WG_AREA.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.MAP_LEVEL
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.MAP_LEVEL
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public String getMapLevel() {
        return mapLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.MAP_LEVEL
     *
     * @param mapLevel the value for C##JXYD_ZHWG.WG_AREA.MAP_LEVEL
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setMapLevel(String mapLevel) {
        this.mapLevel = mapLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_INFO
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.AREA_INFO
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public String getAreaInfo() {
        return areaInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_INFO
     *
     * @param areaInfo the value for C##JXYD_ZHWG.WG_AREA.AREA_INFO
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setAreaInfo(String areaInfo) {
        this.areaInfo = areaInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.WG_PID
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.WG_PID
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public String getWgPid() {
        return wgPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.WG_PID
     *
     * @param wgPid the value for C##JXYD_ZHWG.WG_AREA.WG_PID
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setWgPid(String wgPid) {
        this.wgPid = wgPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.LEFTTOPX
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.LEFTTOPX
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public Double getLefttopx() {
        return lefttopx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.LEFTTOPX
     *
     * @param lefttopx the value for C##JXYD_ZHWG.WG_AREA.LEFTTOPX
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setLefttopx(Double lefttopx) {
        this.lefttopx = lefttopx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.LEFTTOPY
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.LEFTTOPY
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public Double getLefttopy() {
        return lefttopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.LEFTTOPY
     *
     * @param lefttopy the value for C##JXYD_ZHWG.WG_AREA.LEFTTOPY
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setLefttopy(Double lefttopy) {
        this.lefttopy = lefttopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.RIGHTBOTTOMX
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.RIGHTBOTTOMX
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public Double getRightbottomx() {
        return rightbottomx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.RIGHTBOTTOMX
     *
     * @param rightbottomx the value for C##JXYD_ZHWG.WG_AREA.RIGHTBOTTOMX
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setRightbottomx(Double rightbottomx) {
        this.rightbottomx = rightbottomx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.RIGHTBOTTOMY
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.RIGHTBOTTOMY
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public Double getRightbottomy() {
        return rightbottomy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.RIGHTBOTTOMY
     *
     * @param rightbottomy the value for C##JXYD_ZHWG.WG_AREA.RIGHTBOTTOMY
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setRightbottomy(Double rightbottomy) {
        this.rightbottomy = rightbottomy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.PROC_TIME
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.PROC_TIME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public Date getProcTime() {
        return procTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.PROC_TIME
     *
     * @param procTime the value for C##JXYD_ZHWG.WG_AREA.PROC_TIME
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setProcTime(Date procTime) {
        this.procTime = procTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_LOCATION
     *
     * @return the value of C##JXYD_ZHWG.WG_AREA.AREA_LOCATION
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public String getAreaLocation() {
        return areaLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##JXYD_ZHWG.WG_AREA.AREA_LOCATION
     *
     * @param areaLocation the value for C##JXYD_ZHWG.WG_AREA.AREA_LOCATION
     *
     * @mbg.generated Tue Dec 19 14:17:14 CST 2017
     */
    public void setAreaLocation(String areaLocation) {
        this.areaLocation = areaLocation;
    }

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTeleNum() {
		return teleNum;
	}

	public void setTeleNum(String teleNum) {
		this.teleNum = teleNum;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getUserCode() {
		return userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

    public String getKpiType() {
        return kpiType;
    }

    public void setKpiType(String kpiType) {
        this.kpiType = kpiType;
    }

    public String getKpiValue() {
        return kpiValue;
    }

    public void setKpiValue(String kpiValue) {
        this.kpiValue = kpiValue;
    }
}